name: daily_todo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core dependencies
  auto_route: ^3.2.4
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  dartz: ^0.10.1
  device_preview: ^1.0.0
  material_design_icons_flutter: ^5.0.6595
  flash: ^2.0.3+2
  intl: ^0.17.0

  # theme
  google_fonts: ^2.3.1
  flex_color_scheme: ^4.2.0

  # firebase
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.10
  firebase_database: ^9.0.8

  # authentication
  google_sign_in: ^5.2.4

  # image manipulation
  image_picker: ^0.8.4+11
  image_cropper: ^1.5.0
  cached_network_image: ^3.2.0

  # unit test
  firebase_auth_mocks: ^0.8.2
  google_sign_in_mocks: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  auto_route_generator: ^3.2.3
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
